/**
 * FoxEats — Données de seed Côte d'Azur.
 * Noms de restaurants entièrement inventés. Plats et prix réalistes.
 */

export type SeedRestaurant = {
  slug: string;
  name: string;
  description: string;
  cuisines: string[];
  city: string;
  street: string;
  postalCode: string;
  lat: number;
  lng: number;
  priceRange: 1 | 2 | 3 | 4;
  rating: string;
  ratingCount: number;
  deliveryFeeCents: number;
  deliveryMinCents: number;
  prepTimeMinMinutes: number;
  prepTimeMaxMinutes: number;
  isHalal?: boolean;
  isVegetarianFriendly?: boolean;
  isVeganFriendly?: boolean;
  isLocalSpecialty?: boolean;
  isAntiWasteEnabled?: boolean;
  coverPicsumSeed: string;
  categories: SeedCategory[];
};

export type SeedCategory = {
  name: string;
  items: SeedItem[];
};

export type SeedItem = {
  name: string;
  description?: string;
  priceCents: number;
  isPopular?: boolean;
  isVegetarian?: boolean;
  isVegan?: boolean;
  isGlutenFree?: boolean;
  isSpicy?: boolean;
  isLocalSpecialty?: boolean;
  allergens?: string[];
};

const C = {
  niçoise: 'niçoise',
  french: 'french',
  italian: 'italian',
  pizza: 'pizza',
  japanese: 'japanese',
  sushi: 'sushi',
  burger: 'burger',
  american: 'american',
  healthy: 'healthy',
  vegan: 'vegan',
  vegetarian: 'vegetarian',
  lebanese: 'lebanese',
  mexican: 'mexican',
  mediterranean: 'mediterranean',
  bakery: 'bakery',
  dessert: 'dessert',
  thai: 'thai',
  indian: 'indian',
  seafood: 'seafood',
} as const;

// Plats locaux signature pour catégorie "Spécialités niçoises"
const NICOISE_SPECIALTIES: SeedItem[] = [
  {
    name: 'Socca',
    description: 'La galette de pois chiches cuite au feu de bois, fumée et craquante.',
    priceCents: 450,
    isVegan: true,
    isGlutenFree: true,
    isLocalSpecialty: true,
    isPopular: true,
  },
  {
    name: 'Pissaladière',
    description: 'Pâte fine, oignons confits, anchois et olives noires de Nice.',
    priceCents: 850,
    isLocalSpecialty: true,
    isPopular: true,
    allergens: ['gluten', 'poisson'],
  },
  {
    name: 'Salade niçoise',
    description: 'Tomates, œuf, olives, thon, haricots verts, basilic frais.',
    priceCents: 1400,
    isGlutenFree: true,
    isLocalSpecialty: true,
    isPopular: true,
    allergens: ['oeuf', 'poisson'],
  },
  {
    name: 'Pan-bagnat',
    description: "Pain rond gorgé d'huile d'olive, garni à la niçoise.",
    priceCents: 950,
    isLocalSpecialty: true,
    allergens: ['gluten', 'oeuf', 'poisson'],
  },
  {
    name: 'Daube à la niçoise',
    description: "Bœuf mijoté longuement au vin rouge et zestes d'orange, polenta crémeuse.",
    priceCents: 2200,
    isLocalSpecialty: true,
  },
  {
    name: 'Tourte de blettes salée',
    description: 'Pâte fine, blettes, pignons, parmesan.',
    priceCents: 880,
    isVegetarian: true,
    isLocalSpecialty: true,
    allergens: ['gluten', 'oeuf', 'lait'],
  },
  {
    name: 'Tourte de blettes sucrée',
    description: 'La version dessert: blettes, raisins secs, pignons, sucre.',
    priceCents: 720,
    isVegetarian: true,
    isLocalSpecialty: true,
    allergens: ['gluten', 'oeuf', 'fruits-coque'],
  },
  {
    name: 'Petits farcis niçois',
    description: 'Légumes du soleil farcis: courgette, tomate, oignon, poivron.',
    priceCents: 1650,
    isLocalSpecialty: true,
    allergens: ['gluten', 'oeuf', 'lait'],
  },
];

export const RIVIERA_RESTAURANTS: SeedRestaurant[] = [
  // ─── NICE (8) ─────────────────────────────────────────────────────────────
  {
    slug: 'la-petite-socca',
    name: 'La Petite Socca',
    description: 'Cuisine niçoise traditionnelle dans le Vieux-Nice, recettes de grand-mère.',
    cuisines: [C.niçoise, C.french, C.mediterranean],
    city: 'Nice',
    street: '18 rue Pairolière',
    postalCode: '06300',
    lat: 43.6995,
    lng: 7.276,
    priceRange: 2,
    rating: '4.7',
    ratingCount: 312,
    deliveryFeeCents: 299,
    deliveryMinCents: 1200,
    prepTimeMinMinutes: 20,
    prepTimeMaxMinutes: 35,
    isLocalSpecialty: true,
    isVegetarianFriendly: true,
    coverPicsumSeed: 'nicoise-socca',
    categories: [
      { name: 'Spécialités niçoises', items: NICOISE_SPECIALTIES.slice(0, 6) },
      {
        name: 'Pour partager',
        items: [
          {
            name: 'Olives Caillette de Nice',
            description: "AOP, marinade huile d'olive et thym.",
            priceCents: 580,
            isVegan: true,
            isGlutenFree: true,
          },
          {
            name: 'Anchoïade et crudités',
            description: 'Sauce aux anchois et légumes croquants.',
            priceCents: 850,
            allergens: ['poisson'],
          },
          {
            name: 'Tapenade noire',
            description: 'Olives noires, câpres, anchois.',
            priceCents: 780,
            allergens: ['poisson'],
          },
        ],
      },
      {
        name: 'Douceurs',
        items: [
          {
            name: 'Tourte de blettes sucrée',
            description: 'La spécialité du dimanche.',
            priceCents: 720,
            isVegetarian: true,
            isLocalSpecialty: true,
            allergens: ['gluten', 'oeuf', 'fruits-coque'],
          },
          {
            name: 'Tarte au citron de Menton',
            description: 'Crème citron, meringue légère.',
            priceCents: 680,
            isVegetarian: true,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
        ],
      },
    ],
  },
  {
    slug: 'lazur-pizzeria',
    name: "L'Azur Pizzeria",
    description: 'Pizza napolitaine au feu de bois, pâte 48h, farine T00.',
    cuisines: [C.italian, C.pizza],
    city: 'Nice',
    street: '7 rue Masséna',
    postalCode: '06000',
    lat: 43.6976,
    lng: 7.2671,
    priceRange: 2,
    rating: '4.6',
    ratingCount: 521,
    deliveryFeeCents: 249,
    deliveryMinCents: 1000,
    prepTimeMinMinutes: 18,
    prepTimeMaxMinutes: 28,
    isVegetarianFriendly: true,
    coverPicsumSeed: 'nice-pizza',
    categories: [
      {
        name: 'Pizzas signature',
        items: [
          {
            name: 'Margherita DOP',
            description: 'Tomate San Marzano, mozzarella di bufala, basilic.',
            priceCents: 1290,
            isPopular: true,
            isVegetarian: true,
            allergens: ['gluten', 'lait'],
          },
          {
            name: 'Diavola',
            description: 'Tomate, mozzarella, salami piquant calabrais.',
            priceCents: 1450,
            isSpicy: true,
            allergens: ['gluten', 'lait'],
          },
          {
            name: 'Quattro Formaggi',
            description: 'Mozzarella, gorgonzola, parmesan, scamorza.',
            priceCents: 1490,
            isVegetarian: true,
            allergens: ['gluten', 'lait'],
          },
          {
            name: 'Tartufata',
            description: 'Crème de truffe, mozzarella, jambon de Parme, roquette.',
            priceCents: 1890,
            isPopular: true,
            allergens: ['gluten', 'lait'],
          },
          {
            name: 'Niçoise (signature)',
            description: 'Tomate, anchois, olives de Nice, oignons confits.',
            priceCents: 1490,
            isLocalSpecialty: true,
            allergens: ['gluten', 'poisson'],
          },
        ],
      },
      {
        name: 'Entrées',
        items: [
          {
            name: 'Burrata des Pouilles',
            description: 'Burrata fraîche, tomates anciennes, basilic.',
            priceCents: 1290,
            isVegetarian: true,
            allergens: ['lait'],
          },
          {
            name: 'Antipasti maison',
            description: 'Charcuterie italienne, marinades, focaccia.',
            priceCents: 1490,
            allergens: ['gluten', 'lait'],
          },
        ],
      },
      {
        name: 'Desserts',
        items: [
          {
            name: 'Tiramisu',
            description: 'Recette de la nonna, mascarpone, café fort.',
            priceCents: 690,
            isVegetarian: true,
            isPopular: true,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
          {
            name: 'Panna cotta citron de Menton',
            description: '',
            priceCents: 590,
            isVegetarian: true,
            allergens: ['lait'],
          },
        ],
      },
    ],
  },
  {
    slug: 'sakura-ramen-house',
    name: 'Sakura Ramen House',
    description: 'Ramens tonkotsu et shoyu, gyozas maison, bouillons 12h.',
    cuisines: [C.japanese],
    city: 'Nice',
    street: '24 rue Hôtel des Postes',
    postalCode: '06000',
    lat: 43.7016,
    lng: 7.2701,
    priceRange: 2,
    rating: '4.5',
    ratingCount: 198,
    deliveryFeeCents: 349,
    deliveryMinCents: 1500,
    prepTimeMinMinutes: 20,
    prepTimeMaxMinutes: 30,
    coverPicsumSeed: 'nice-ramen',
    categories: [
      {
        name: 'Ramens',
        items: [
          {
            name: 'Tonkotsu',
            description: 'Bouillon de porc 12h, nouilles fines, chashu, œuf mariné.',
            priceCents: 1690,
            isPopular: true,
            allergens: ['gluten', 'oeuf', 'soja'],
          },
          {
            name: 'Shoyu Poulet',
            description: 'Bouillon clair sauce soja, poulet rôti.',
            priceCents: 1590,
            allergens: ['gluten', 'oeuf', 'soja'],
          },
          {
            name: 'Spicy Miso',
            description: 'Bouillon corsé miso rouge, porc haché, ciboule.',
            priceCents: 1690,
            isSpicy: true,
            allergens: ['gluten', 'soja'],
          },
          {
            name: 'Veggie Mushroom',
            description: 'Bouillon dashi végétal, shiitake, tofu.',
            priceCents: 1590,
            isVegetarian: true,
            allergens: ['gluten', 'soja'],
          },
        ],
      },
      {
        name: 'À côté',
        items: [
          {
            name: 'Gyozas porc (6)',
            description: '',
            priceCents: 690,
            allergens: ['gluten', 'soja'],
          },
          {
            name: 'Edamame',
            description: 'Fève de soja, fleur de sel.',
            priceCents: 480,
            isVegan: true,
            isGlutenFree: true,
            allergens: ['soja'],
          },
          {
            name: 'Karaage',
            description: 'Poulet frit japonais, mayo yuzu.',
            priceCents: 890,
            allergens: ['gluten', 'oeuf'],
          },
        ],
      },
    ],
  },
  {
    slug: 'le-comptoir-vert',
    name: 'Le Comptoir Vert',
    description: 'Bowls healthy, jus pressés à froid, salades du marché niçois.',
    cuisines: [C.healthy, C.vegan, C.vegetarian],
    city: 'Nice',
    street: '12 avenue Jean Médecin',
    postalCode: '06000',
    lat: 43.7034,
    lng: 7.2671,
    priceRange: 2,
    rating: '4.4',
    ratingCount: 156,
    deliveryFeeCents: 299,
    deliveryMinCents: 1200,
    prepTimeMinMinutes: 12,
    prepTimeMaxMinutes: 20,
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    coverPicsumSeed: 'nice-bowl',
    categories: [
      {
        name: 'Bowls',
        items: [
          {
            name: 'Buddha bowl quinoa',
            description: 'Quinoa, avocat, edamame, patate douce, sésame.',
            priceCents: 1390,
            isVegan: true,
            isGlutenFree: true,
            isPopular: true,
          },
          {
            name: 'Poke bowl saumon',
            description: 'Riz, saumon mariné, mangue, avocat.',
            priceCents: 1590,
            isGlutenFree: true,
            allergens: ['poisson', 'soja'],
          },
          {
            name: 'Méditerranée bowl',
            description: 'Houmous, falafels, courgettes grillées, boulgour.',
            priceCents: 1390,
            isVegan: true,
            allergens: ['gluten', 'sésame'],
          },
        ],
      },
      {
        name: 'Jus & smoothies',
        items: [
          {
            name: 'Detox vert',
            description: 'Concombre, pomme verte, citron, menthe.',
            priceCents: 690,
            isVegan: true,
            isGlutenFree: true,
            isPopular: true,
          },
          {
            name: 'Riviera sunrise',
            description: 'Mangue, orange sanguine, gingembre.',
            priceCents: 690,
            isVegan: true,
            isGlutenFree: true,
          },
        ],
      },
    ],
  },
  {
    slug: 'maison-rossi',
    name: 'Maison Rossi',
    description: 'Bistrot français contemporain, produits de Méditerranée.',
    cuisines: [C.french, C.mediterranean],
    city: 'Nice',
    street: '5 rue de la Préfecture',
    postalCode: '06300',
    lat: 43.6964,
    lng: 7.275,
    priceRange: 3,
    rating: '4.8',
    ratingCount: 287,
    deliveryFeeCents: 399,
    deliveryMinCents: 2000,
    prepTimeMinMinutes: 30,
    prepTimeMaxMinutes: 45,
    coverPicsumSeed: 'nice-bistrot',
    categories: [
      {
        name: 'Entrées',
        items: [
          {
            name: 'Carpaccio de daurade',
            description: "Daurade royale, citron de Menton, huile d'olive Nyons.",
            priceCents: 1450,
            isGlutenFree: true,
            allergens: ['poisson'],
          },
          {
            name: 'Petits farcis niçois',
            description: 'La signature de la maison.',
            priceCents: 1650,
            isLocalSpecialty: true,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
        ],
      },
      {
        name: 'Plats',
        items: [
          {
            name: 'Loup grillé à la plancha',
            description: 'Légumes du jour, sauce vierge.',
            priceCents: 2890,
            isPopular: true,
            isGlutenFree: true,
            allergens: ['poisson'],
          },
          {
            name: 'Daube niçoise',
            description: 'La recette ancestrale.',
            priceCents: 2290,
            isLocalSpecialty: true,
          },
          {
            name: "Risotto à la truffe d'été",
            description: 'Carnaroli, parmesan affiné 24 mois.',
            priceCents: 2490,
            isVegetarian: true,
            isGlutenFree: true,
            allergens: ['lait'],
          },
        ],
      },
      {
        name: 'Desserts',
        items: [
          {
            name: 'Tarte au citron de Menton',
            description: '',
            priceCents: 890,
            isVegetarian: true,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
          {
            name: 'Soufflé chocolat Valrhona',
            description: 'À commander 20 min avant.',
            priceCents: 1090,
            isVegetarian: true,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
        ],
      },
    ],
  },
  {
    slug: 'el-jardin-cantina',
    name: 'El Jardín Cantina',
    description: 'Tacos, burritos, guacamole frais, vibes mexicaines.',
    cuisines: [C.mexican],
    city: 'Nice',
    street: '33 rue de France',
    postalCode: '06000',
    lat: 43.6953,
    lng: 7.262,
    priceRange: 2,
    rating: '4.3',
    ratingCount: 174,
    deliveryFeeCents: 299,
    deliveryMinCents: 1000,
    prepTimeMinMinutes: 15,
    prepTimeMaxMinutes: 25,
    isVegetarianFriendly: true,
    coverPicsumSeed: 'nice-mex',
    categories: [
      {
        name: 'Tacos',
        items: [
          {
            name: 'Carne asada (3)',
            description: 'Bœuf grillé, coriandre, oignon rouge, lime.',
            priceCents: 1290,
            isPopular: true,
            allergens: ['gluten'],
          },
          {
            name: 'Al pastor (3)',
            description: 'Porc mariné, ananas, salsa verde.',
            priceCents: 1290,
            isSpicy: true,
            allergens: ['gluten'],
          },
          {
            name: 'Tofu chipotle (3)',
            description: 'Tofu fumé, salsa, avocat.',
            priceCents: 1190,
            isVegan: true,
            allergens: ['gluten', 'soja'],
          },
        ],
      },
      {
        name: 'À partager',
        items: [
          {
            name: 'Guacamole frais',
            description: 'Avocat écrasé minute, tortillas maison.',
            priceCents: 890,
            isVegan: true,
            isGlutenFree: true,
          },
          {
            name: 'Nachos suprêmes',
            description: 'Fromage, jalapeños, salsa, crème.',
            priceCents: 1090,
            isVegetarian: true,
            isSpicy: true,
            allergens: ['lait'],
          },
        ],
      },
    ],
  },
  {
    slug: 'beirut-by-the-sea',
    name: 'Beirut by the Sea',
    description: 'Mezzés libanais, grillades, recettes familiales.',
    cuisines: [C.lebanese, C.mediterranean],
    city: 'Nice',
    street: '28 quai des États-Unis',
    postalCode: '06300',
    lat: 43.6938,
    lng: 7.273,
    priceRange: 2,
    rating: '4.6',
    ratingCount: 224,
    deliveryFeeCents: 299,
    deliveryMinCents: 1200,
    prepTimeMinMinutes: 20,
    prepTimeMaxMinutes: 30,
    isHalal: true,
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    coverPicsumSeed: 'nice-lebanese',
    categories: [
      {
        name: 'Mezzés',
        items: [
          {
            name: 'Houmous',
            description: 'Pois chiches, tahini, citron.',
            priceCents: 680,
            isVegan: true,
            allergens: ['sésame'],
          },
          {
            name: 'Falafels (6)',
            description: 'Croquants, herbes fraîches, sauce blanche.',
            priceCents: 890,
            isVegan: true,
            isPopular: true,
            allergens: ['gluten', 'sésame'],
          },
          {
            name: 'Taboulé libanais',
            description: 'Persil, menthe, boulgour, tomate.',
            priceCents: 790,
            isVegan: true,
            allergens: ['gluten'],
          },
          {
            name: 'Baba ghanouj',
            description: 'Aubergine fumée au tahini.',
            priceCents: 720,
            isVegan: true,
            allergens: ['sésame'],
          },
        ],
      },
      {
        name: 'Grillades',
        items: [
          {
            name: 'Brochette de poulet shish taouk',
            description: 'Pain libanais, sauce ail.',
            priceCents: 1690,
            allergens: ['gluten', 'lait'],
          },
          {
            name: "Brochette d'agneau kafta",
            description: 'Agneau haché aux épices.',
            priceCents: 1890,
            isPopular: true,
            allergens: ['gluten'],
          },
        ],
      },
      {
        name: 'Desserts',
        items: [
          {
            name: 'Baklava (4 pièces)',
            description: "Pistache, sirop de fleur d'oranger.",
            priceCents: 690,
            isVegetarian: true,
            allergens: ['gluten', 'fruits-coque'],
          },
        ],
      },
    ],
  },
  {
    slug: 'big-bay-burger',
    name: 'Big Bay Burger',
    description: 'Smash burgers, frites maison, milkshakes épais.',
    cuisines: [C.burger, C.american],
    city: 'Nice',
    street: '14 rue Halévy',
    postalCode: '06000',
    lat: 43.696,
    lng: 7.2655,
    priceRange: 2,
    rating: '4.5',
    ratingCount: 412,
    deliveryFeeCents: 299,
    deliveryMinCents: 1200,
    prepTimeMinMinutes: 15,
    prepTimeMaxMinutes: 25,
    isVegetarianFriendly: true,
    coverPicsumSeed: 'nice-burger',
    categories: [
      {
        name: 'Smash burgers',
        items: [
          {
            name: 'The OG',
            description: 'Double smash, cheddar, cornichons, sauce maison.',
            priceCents: 1290,
            isPopular: true,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
          {
            name: 'Truffle Bacon',
            description: 'Double smash, bacon, mayo truffe.',
            priceCents: 1590,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
          {
            name: 'Beyond Smash',
            description: 'Galette végétale, vegan cheese.',
            priceCents: 1390,
            isVegan: true,
            allergens: ['gluten', 'soja'],
          },
        ],
      },
      {
        name: 'Sides',
        items: [
          { name: 'Frites maison', description: '', priceCents: 490, isVegan: true },
          {
            name: 'Onion rings',
            description: '',
            priceCents: 590,
            isVegetarian: true,
            allergens: ['gluten', 'oeuf'],
          },
        ],
      },
      {
        name: 'Milkshakes',
        items: [
          {
            name: 'Vanille bourbon',
            description: '',
            priceCents: 690,
            isVegetarian: true,
            allergens: ['lait'],
          },
          {
            name: 'Cookies & cream',
            description: '',
            priceCents: 790,
            isVegetarian: true,
            allergens: ['gluten', 'lait', 'oeuf'],
          },
        ],
      },
    ],
  },

  // ─── CANNES (5) ────────────────────────────────────────────────────────────
  {
    slug: 'la-croisette-grill',
    name: 'La Croisette Grill',
    description: 'Brasserie chic, poissons grillés, vue sur la Méditerranée.',
    cuisines: [C.french, C.seafood, C.mediterranean],
    city: 'Cannes',
    street: '45 boulevard de la Croisette',
    postalCode: '06400',
    lat: 43.5503,
    lng: 7.0192,
    priceRange: 3,
    rating: '4.6',
    ratingCount: 389,
    deliveryFeeCents: 399,
    deliveryMinCents: 2500,
    prepTimeMinMinutes: 25,
    prepTimeMaxMinutes: 40,
    coverPicsumSeed: 'cannes-grill',
    categories: [
      {
        name: 'Entrées',
        items: [
          {
            name: 'Tartare de thon rouge',
            description: 'Mangue, avocat, sésame.',
            priceCents: 1690,
            allergens: ['poisson', 'sésame'],
          },
          {
            name: 'Burrata & melon',
            description: '',
            priceCents: 1390,
            isVegetarian: true,
            allergens: ['lait'],
          },
        ],
      },
      {
        name: 'Plats',
        items: [
          {
            name: 'Daurade royale entière',
            description: 'À la plancha, citron confit.',
            priceCents: 2890,
            isPopular: true,
            isGlutenFree: true,
            allergens: ['poisson'],
          },
          {
            name: 'Linguine aux palourdes',
            description: 'Vongole, vin blanc, persil.',
            priceCents: 2290,
            allergens: ['gluten', 'mollusques'],
          },
        ],
      },
    ],
  },
  {
    slug: 'palme-dor-pizza',
    name: "Palme d'Or Pizza",
    description: 'Pizzas créatives signatures, ingrédients premium.',
    cuisines: [C.italian, C.pizza],
    city: 'Cannes',
    street: '12 rue Hoche',
    postalCode: '06400',
    lat: 43.5524,
    lng: 7.014,
    priceRange: 2,
    rating: '4.5',
    ratingCount: 267,
    deliveryFeeCents: 299,
    deliveryMinCents: 1200,
    prepTimeMinMinutes: 18,
    prepTimeMaxMinutes: 28,
    isVegetarianFriendly: true,
    coverPicsumSeed: 'cannes-pizza',
    categories: [
      {
        name: 'Pizzas',
        items: [
          {
            name: 'Margherita Extra',
            description: "Tomate, bufala, basilic, huile d'olive Provence.",
            priceCents: 1390,
            isVegetarian: true,
            allergens: ['gluten', 'lait'],
          },
          {
            name: 'Tartufo Nero',
            description: 'Crème truffe, parmesan, jambon cru.',
            priceCents: 1990,
            isPopular: true,
            allergens: ['gluten', 'lait'],
          },
          {
            name: 'Cannes Riviera',
            description: 'Anchois, oignons confits, olives, basilic.',
            priceCents: 1590,
            isLocalSpecialty: true,
            allergens: ['gluten', 'poisson'],
          },
        ],
      },
    ],
  },
  {
    slug: 'sushi-noir-cannes',
    name: 'Sushi Noir',
    description: 'Omakase, sashimis de Méditerranée, riz vinaigré.',
    cuisines: [C.japanese, C.sushi],
    city: 'Cannes',
    street: '28 rue Macé',
    postalCode: '06400',
    lat: 43.5494,
    lng: 7.018,
    priceRange: 3,
    rating: '4.7',
    ratingCount: 198,
    deliveryFeeCents: 399,
    deliveryMinCents: 2500,
    prepTimeMinMinutes: 20,
    prepTimeMaxMinutes: 35,
    coverPicsumSeed: 'cannes-sushi',
    categories: [
      {
        name: 'Sashimi',
        items: [
          {
            name: 'Thon rouge (5 pcs)',
            description: '',
            priceCents: 1890,
            isGlutenFree: true,
            allergens: ['poisson'],
          },
          {
            name: 'Saumon Atlantique (5 pcs)',
            description: '',
            priceCents: 1390,
            isGlutenFree: true,
            allergens: ['poisson'],
          },
          {
            name: 'Daurade royale (5 pcs)',
            description: '',
            priceCents: 1590,
            isGlutenFree: true,
            allergens: ['poisson'],
          },
        ],
      },
      {
        name: 'Sushi sets',
        items: [
          {
            name: "Chef's selection (16 pcs)",
            description: 'Mix sashimi, nigiri, makis.',
            priceCents: 3690,
            isPopular: true,
            allergens: ['poisson', 'sésame', 'soja'],
          },
          {
            name: 'Veggie box (12 pcs)',
            description: 'Avocat, concombre, mangue, asperge.',
            priceCents: 1890,
            isVegan: true,
            allergens: ['sésame', 'soja'],
          },
        ],
      },
    ],
  },
  {
    slug: 'cafe-mistral',
    name: 'Café Mistral',
    description: 'Cuisine provençale, salades fraîches, vins du sud.',
    cuisines: [C.french, C.mediterranean, C.niçoise],
    city: 'Cannes',
    street: '6 rue Florian',
    postalCode: '06400',
    lat: 43.5506,
    lng: 7.0202,
    priceRange: 2,
    rating: '4.4',
    ratingCount: 145,
    deliveryFeeCents: 299,
    deliveryMinCents: 1500,
    prepTimeMinMinutes: 20,
    prepTimeMaxMinutes: 30,
    isVegetarianFriendly: true,
    isLocalSpecialty: true,
    coverPicsumSeed: 'cannes-cafe',
    categories: [
      {
        name: 'Plats du jour',
        items: [
          {
            name: 'Salade niçoise',
            description: '',
            priceCents: 1490,
            isLocalSpecialty: true,
            isGlutenFree: true,
            allergens: ['oeuf', 'poisson'],
          },
          {
            name: 'Ratatouille maison',
            description: 'Légumes confits longuement, riz parfumé.',
            priceCents: 1290,
            isVegan: true,
            isGlutenFree: true,
          },
          {
            name: 'Loup en croûte de sel',
            description: '',
            priceCents: 2590,
            isGlutenFree: true,
            allergens: ['poisson'],
          },
        ],
      },
    ],
  },
  {
    slug: 'matcha-and-mango',
    name: 'Matcha & Mango',
    description: 'Pâtisseries asiatiques, mochis, glaces artisanales.',
    cuisines: [C.dessert, C.bakery],
    city: 'Cannes',
    street: "21 rue d'Antibes",
    postalCode: '06400',
    lat: 43.5516,
    lng: 7.0166,
    priceRange: 2,
    rating: '4.6',
    ratingCount: 312,
    deliveryFeeCents: 249,
    deliveryMinCents: 800,
    prepTimeMinMinutes: 10,
    prepTimeMaxMinutes: 20,
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    coverPicsumSeed: 'cannes-dessert',
    categories: [
      {
        name: 'Mochis',
        items: [
          {
            name: 'Mochi matcha (3)',
            description: '',
            priceCents: 690,
            isVegetarian: true,
            allergens: ['lait'],
          },
          {
            name: 'Mochi mangue (3)',
            description: '',
            priceCents: 690,
            isVegetarian: true,
            allergens: ['lait'],
          },
          {
            name: 'Mochi cacahuète (3)',
            description: '',
            priceCents: 690,
            isVegetarian: true,
            isPopular: true,
            allergens: ['lait', 'fruits-coque'],
          },
        ],
      },
      {
        name: 'Glaces',
        items: [
          {
            name: 'Sorbet citron de Menton',
            description: '',
            priceCents: 490,
            isVegan: true,
            isGlutenFree: true,
            isLocalSpecialty: true,
          },
          {
            name: 'Glace pistache de Sicile',
            description: '',
            priceCents: 590,
            isVegetarian: true,
            isGlutenFree: true,
            allergens: ['lait', 'fruits-coque'],
          },
        ],
      },
    ],
  },

  // ─── ANTIBES (4) ───────────────────────────────────────────────────────────
  {
    slug: 'le-port-vauban',
    name: 'Le Port Vauban',
    description: 'Poissonnerie-bistrot face au port, criée du jour.',
    cuisines: [C.seafood, C.french, C.mediterranean],
    city: 'Antibes',
    street: '11 quai des Pêcheurs',
    postalCode: '06600',
    lat: 43.5825,
    lng: 7.1273,
    priceRange: 3,
    rating: '4.7',
    ratingCount: 256,
    deliveryFeeCents: 349,
    deliveryMinCents: 2000,
    prepTimeMinMinutes: 25,
    prepTimeMaxMinutes: 40,
    coverPicsumSeed: 'antibes-port',
    categories: [
      {
        name: 'Du jour',
        items: [
          {
            name: 'Bouillabaisse traditionnelle',
            description: 'Rouille, croûtons, gruyère.',
            priceCents: 2890,
            isPopular: true,
            isLocalSpecialty: true,
            allergens: ['gluten', 'poisson', 'crustacés', 'lait'],
          },
          {
            name: 'Plateau de fruits de mer',
            description: 'Huîtres, langoustines, crabe, palourdes.',
            priceCents: 4290,
            isGlutenFree: true,
            allergens: ['crustacés', 'mollusques'],
          },
          {
            name: 'Poisson du jour grillé',
            description: 'Selon arrivage.',
            priceCents: 2790,
            isGlutenFree: true,
            allergens: ['poisson'],
          },
        ],
      },
    ],
  },
  {
    slug: 'casa-picasso',
    name: 'Casa Picasso',
    description: 'Tapas, ibérique, sangria. Cuisine du soleil.',
    cuisines: [C.mediterranean],
    city: 'Antibes',
    street: '5 rue Sade',
    postalCode: '06600',
    lat: 43.5806,
    lng: 7.1244,
    priceRange: 2,
    rating: '4.4',
    ratingCount: 187,
    deliveryFeeCents: 299,
    deliveryMinCents: 1500,
    prepTimeMinMinutes: 20,
    prepTimeMaxMinutes: 30,
    coverPicsumSeed: 'antibes-tapas',
    categories: [
      {
        name: 'Tapas',
        items: [
          { name: 'Pata Negra Bellota', description: '50g, affiné 36 mois.', priceCents: 1690 },
          {
            name: 'Patatas bravas',
            description: '',
            priceCents: 690,
            isVegetarian: true,
            allergens: ['oeuf'],
          },
          {
            name: 'Croquetas jamón',
            description: 'Béchamel, jambon ibérique.',
            priceCents: 890,
            allergens: ['gluten', 'lait', 'oeuf'],
          },
          {
            name: 'Tortilla maison',
            description: '',
            priceCents: 790,
            isVegetarian: true,
            isGlutenFree: true,
            allergens: ['oeuf'],
          },
        ],
      },
    ],
  },
  {
    slug: 'kebab-istanbul',
    name: "Kebab d'Istanbul",
    description: 'Kebabs traditionnels, viande de qualité, pain frais.',
    cuisines: [C.lebanese, C.mediterranean],
    city: 'Antibes',
    street: '14 rue de la République',
    postalCode: '06600',
    lat: 43.5811,
    lng: 7.1259,
    priceRange: 1,
    rating: '4.3',
    ratingCount: 423,
    deliveryFeeCents: 249,
    deliveryMinCents: 800,
    prepTimeMinMinutes: 12,
    prepTimeMaxMinutes: 20,
    isHalal: true,
    coverPicsumSeed: 'antibes-kebab',
    categories: [
      {
        name: 'Kebabs',
        items: [
          {
            name: 'Döner classique',
            description: 'Veau-agneau, salade, sauce blanche.',
            priceCents: 890,
            allergens: ['gluten', 'lait'],
          },
          { name: 'Döner XXL', description: '', priceCents: 1090, allergens: ['gluten', 'lait'] },
          {
            name: 'Galette poulet',
            description: '',
            priceCents: 950,
            isPopular: true,
            allergens: ['gluten', 'lait'],
          },
        ],
      },
    ],
  },
  {
    slug: 'cap-vegan',
    name: 'Cap Vegan',
    description: '100% végétal, créatif, du marché local.',
    cuisines: [C.vegan, C.healthy],
    city: 'Antibes',
    street: "22 boulevard d'Aguillon",
    postalCode: '06600',
    lat: 43.5798,
    lng: 7.1281,
    priceRange: 2,
    rating: '4.5',
    ratingCount: 134,
    deliveryFeeCents: 299,
    deliveryMinCents: 1500,
    prepTimeMinMinutes: 18,
    prepTimeMaxMinutes: 28,
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    coverPicsumSeed: 'antibes-vegan',
    categories: [
      {
        name: 'Plats',
        items: [
          {
            name: 'Bowl tempeh BBQ',
            description: 'Tempeh laqué, riz noir, légumes rôtis.',
            priceCents: 1490,
            isVegan: true,
            allergens: ['soja', 'gluten'],
          },
          {
            name: 'Curry de pois chiches',
            description: 'Lait de coco, riz basmati.',
            priceCents: 1390,
            isVegan: true,
            isGlutenFree: true,
            isSpicy: true,
          },
          {
            name: 'Lasagnes végétales',
            description: 'Aubergines, ricotta de cajou.',
            priceCents: 1390,
            isVegan: true,
            allergens: ['gluten', 'fruits-coque'],
          },
        ],
      },
    ],
  },

  // ─── MONACO (3) ────────────────────────────────────────────────────────────
  {
    slug: 'monte-carlo-grand',
    name: 'Monte-Carlo Grand',
    description: 'Gastronomie raffinée, terrasse vue mer.',
    cuisines: [C.french, C.mediterranean],
    city: 'Monaco',
    street: '17 avenue de la Costa',
    postalCode: '98000',
    lat: 43.7382,
    lng: 7.4282,
    priceRange: 4,
    rating: '4.8',
    ratingCount: 178,
    deliveryFeeCents: 599,
    deliveryMinCents: 4000,
    prepTimeMinMinutes: 35,
    prepTimeMaxMinutes: 55,
    coverPicsumSeed: 'monaco-grand',
    categories: [
      {
        name: 'Menu signature',
        items: [
          {
            name: 'Tartare de bœuf Black Angus',
            description: 'Coupé au couteau, huile de truffe.',
            priceCents: 3290,
            allergens: ['oeuf'],
          },
          {
            name: 'Loup en croûte',
            description: 'Sauce hollandaise.',
            priceCents: 4290,
            isPopular: true,
            allergens: ['poisson', 'oeuf', 'lait'],
          },
          {
            name: 'Tournedos Rossini',
            description: 'Foie gras, sauce périgueux.',
            priceCents: 4890,
            allergens: ['lait'],
          },
        ],
      },
    ],
  },
  {
    slug: 'pasta-fresca',
    name: 'Pasta Fresca',
    description: "Pâtes fraîches, recettes du nord de l'Italie.",
    cuisines: [C.italian],
    city: 'Monaco',
    street: '6 rue Princesse Caroline',
    postalCode: '98000',
    lat: 43.7361,
    lng: 7.4214,
    priceRange: 3,
    rating: '4.6',
    ratingCount: 224,
    deliveryFeeCents: 399,
    deliveryMinCents: 2000,
    prepTimeMinMinutes: 22,
    prepTimeMaxMinutes: 35,
    isVegetarianFriendly: true,
    coverPicsumSeed: 'monaco-pasta',
    categories: [
      {
        name: 'Pâtes fraîches',
        items: [
          {
            name: 'Tagliatelle truffe',
            description: 'Truffe noire, parmesan 24 mois.',
            priceCents: 2390,
            isVegetarian: true,
            isPopular: true,
            allergens: ['gluten', 'lait', 'oeuf'],
          },
          {
            name: 'Ravioli ricotta-épinards',
            description: 'Sauge, beurre noisette.',
            priceCents: 1890,
            isVegetarian: true,
            allergens: ['gluten', 'lait', 'oeuf'],
          },
          {
            name: 'Linguine vongole',
            description: 'Palourdes, vin blanc.',
            priceCents: 2190,
            allergens: ['gluten', 'mollusques'],
          },
        ],
      },
    ],
  },
  {
    slug: 'azur-poke',
    name: 'Azur Poke',
    description: 'Poke bowls hawaïens, options premium.',
    cuisines: [C.healthy],
    city: 'Monaco',
    street: '4 avenue Saint-Charles',
    postalCode: '98000',
    lat: 43.7393,
    lng: 7.42,
    priceRange: 2,
    rating: '4.4',
    ratingCount: 156,
    deliveryFeeCents: 349,
    deliveryMinCents: 1500,
    prepTimeMinMinutes: 12,
    prepTimeMaxMinutes: 20,
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    coverPicsumSeed: 'monaco-poke',
    categories: [
      {
        name: 'Bowls',
        items: [
          {
            name: 'Aloha Tuna',
            description: 'Thon rouge, mangue, edamame.',
            priceCents: 1690,
            isPopular: true,
            allergens: ['poisson', 'soja', 'sésame'],
          },
          {
            name: 'Salmon Tropical',
            description: 'Saumon, ananas, avocat.',
            priceCents: 1590,
            allergens: ['poisson', 'soja'],
          },
          {
            name: 'Veggie Buddha',
            description: 'Tofu, mangue, edamame.',
            priceCents: 1390,
            isVegan: true,
            allergens: ['soja'],
          },
        ],
      },
    ],
  },

  // ─── MENTON (3) ────────────────────────────────────────────────────────────
  {
    slug: 'citron-soleil',
    name: 'Citron Soleil',
    description: 'Cuisine du Pays mentonnais, citron de Menton AOC.',
    cuisines: [C.french, C.niçoise, C.mediterranean],
    city: 'Menton',
    street: '8 rue Saint-Michel',
    postalCode: '06500',
    lat: 43.7765,
    lng: 7.5054,
    priceRange: 2,
    rating: '4.7',
    ratingCount: 198,
    deliveryFeeCents: 299,
    deliveryMinCents: 1500,
    prepTimeMinMinutes: 22,
    prepTimeMaxMinutes: 35,
    isVegetarianFriendly: true,
    isLocalSpecialty: true,
    coverPicsumSeed: 'menton-citron',
    categories: [
      {
        name: 'Plats',
        items: [
          {
            name: 'Pichade mentonnaise',
            description: 'Tarte salée locale, oignons, anchois.',
            priceCents: 990,
            isLocalSpecialty: true,
            allergens: ['gluten', 'poisson'],
          },
          {
            name: 'Daurade au citron de Menton',
            description: '',
            priceCents: 2490,
            isPopular: true,
            isGlutenFree: true,
            allergens: ['poisson'],
          },
          {
            name: 'Barbajuans',
            description: 'Beignets monégasques aux blettes.',
            priceCents: 1290,
            isVegetarian: true,
            isLocalSpecialty: true,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
        ],
      },
      {
        name: 'Desserts',
        items: [
          {
            name: 'Tarte au citron de Menton',
            description: 'La spécialité.',
            priceCents: 790,
            isVegetarian: true,
            isLocalSpecialty: true,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
        ],
      },
    ],
  },
  {
    slug: 'le-jardin-italien',
    name: 'Le Jardin Italien',
    description: 'Trattoria familiale, pasta et pizze.',
    cuisines: [C.italian, C.pizza],
    city: 'Menton',
    street: '20 rue Partouneaux',
    postalCode: '06500',
    lat: 43.7758,
    lng: 7.503,
    priceRange: 2,
    rating: '4.5',
    ratingCount: 152,
    deliveryFeeCents: 299,
    deliveryMinCents: 1200,
    prepTimeMinMinutes: 20,
    prepTimeMaxMinutes: 30,
    isVegetarianFriendly: true,
    coverPicsumSeed: 'menton-italian',
    categories: [
      {
        name: 'Pizze',
        items: [
          {
            name: 'Margherita',
            description: '',
            priceCents: 1290,
            isVegetarian: true,
            allergens: ['gluten', 'lait'],
          },
          {
            name: 'Mentonnaise',
            description: 'Mozzarella, citron de Menton, basilic.',
            priceCents: 1490,
            isVegetarian: true,
            isLocalSpecialty: true,
            allergens: ['gluten', 'lait'],
          },
        ],
      },
      {
        name: 'Pasta',
        items: [
          {
            name: 'Carbonara',
            description: "Guanciale, jaune d'œuf, pecorino.",
            priceCents: 1590,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
          {
            name: 'Arrabbiata',
            description: 'Tomate, ail, piment.',
            priceCents: 1290,
            isVegan: true,
            isSpicy: true,
            allergens: ['gluten'],
          },
        ],
      },
    ],
  },
  {
    slug: 'menton-anti-gaspi',
    name: "L'Atelier Anti-Gaspi",
    description: 'Lots invendus à prix doux, retrait en fin de service.',
    cuisines: [C.french, C.mediterranean],
    city: 'Menton',
    street: '3 quai de Monléon',
    postalCode: '06500',
    lat: 43.7785,
    lng: 7.5072,
    priceRange: 1,
    rating: '4.6',
    ratingCount: 89,
    deliveryFeeCents: 0,
    deliveryMinCents: 0,
    prepTimeMinMinutes: 5,
    prepTimeMaxMinutes: 10,
    isAntiWasteEnabled: true,
    isVegetarianFriendly: true,
    coverPicsumSeed: 'menton-antiwaste',
    categories: [
      {
        name: 'Lots du soir',
        items: [
          {
            name: 'Surprise du chef',
            description: '500g de plats du jour invendus.',
            priceCents: 590,
            isPopular: true,
            allergens: ['gluten', 'lait', 'oeuf'],
          },
          {
            name: 'Panier viennoiseries',
            description: '6 pièces, fournée du matin.',
            priceCents: 490,
            isVegetarian: true,
            allergens: ['gluten', 'lait', 'oeuf'],
          },
        ],
      },
    ],
  },

  // ─── SAINT-TROPEZ (3) ──────────────────────────────────────────────────────
  {
    slug: 'plage-azur',
    name: 'Plage Azur',
    description: 'Beach restaurant, cuisine méditerranéenne, ambiance estivale.',
    cuisines: [C.mediterranean, C.seafood],
    city: 'Saint-Tropez',
    street: 'Route de Pampelonne',
    postalCode: '83350',
    lat: 43.2641,
    lng: 6.6512,
    priceRange: 4,
    rating: '4.5',
    ratingCount: 312,
    deliveryFeeCents: 699,
    deliveryMinCents: 5000,
    prepTimeMinMinutes: 30,
    prepTimeMaxMinutes: 50,
    coverPicsumSeed: 'st-tropez-beach',
    categories: [
      {
        name: 'Du marché',
        items: [
          {
            name: 'Carpaccio de loup',
            description: "Citron, huile d'olive, fleur de sel.",
            priceCents: 1890,
            isGlutenFree: true,
            allergens: ['poisson'],
          },
          {
            name: 'Aïoli traditionnel',
            description: 'Poissons, légumes vapeur, ail.',
            priceCents: 2890,
            isLocalSpecialty: true,
            isGlutenFree: true,
            allergens: ['poisson', 'oeuf'],
          },
          {
            name: 'Pavé de thon mi-cuit',
            description: 'Croûte de sésame, légumes asiatiques.',
            priceCents: 2790,
            allergens: ['poisson', 'sésame', 'soja'],
          },
        ],
      },
      {
        name: 'Tarte tropézienne',
        items: [
          {
            name: 'Tarte tropézienne classique',
            description: "La signature de Saint-Trop'.",
            priceCents: 890,
            isVegetarian: true,
            isPopular: true,
            isLocalSpecialty: true,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
        ],
      },
    ],
  },
  {
    slug: 'boulange-tropezienne',
    name: 'La Boulange Tropézienne',
    description: 'Pains au levain, viennoiseries, tartes du marché.',
    cuisines: [C.bakery, C.dessert],
    city: 'Saint-Tropez',
    street: '12 rue Sibilli',
    postalCode: '83990',
    lat: 43.2728,
    lng: 6.6394,
    priceRange: 2,
    rating: '4.7',
    ratingCount: 234,
    deliveryFeeCents: 249,
    deliveryMinCents: 800,
    prepTimeMinMinutes: 8,
    prepTimeMaxMinutes: 18,
    isVegetarianFriendly: true,
    coverPicsumSeed: 'st-tropez-bakery',
    categories: [
      {
        name: 'Boulangerie',
        items: [
          {
            name: 'Pain au levain (500g)',
            description: '',
            priceCents: 490,
            isVegan: true,
            allergens: ['gluten'],
          },
          {
            name: 'Fougasse aux olives',
            description: '',
            priceCents: 590,
            isVegan: true,
            allergens: ['gluten'],
          },
        ],
      },
      {
        name: 'Sucré',
        items: [
          {
            name: 'Tarte tropézienne (part)',
            description: '',
            priceCents: 690,
            isVegetarian: true,
            isPopular: true,
            isLocalSpecialty: true,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
          {
            name: 'Pain au chocolat',
            description: '',
            priceCents: 290,
            isVegetarian: true,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
          {
            name: 'Tarte aux fraises',
            description: 'Gariguette de Provence.',
            priceCents: 590,
            isVegetarian: true,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
        ],
      },
    ],
  },
  {
    slug: 'tropez-tacos',
    name: 'Tropez Tacos',
    description: "Tacos street-food, vibes Saint-Trop'.",
    cuisines: [C.mexican],
    city: 'Saint-Tropez',
    street: '8 avenue Foch',
    postalCode: '83990',
    lat: 43.2691,
    lng: 6.6388,
    priceRange: 2,
    rating: '4.3',
    ratingCount: 167,
    deliveryFeeCents: 299,
    deliveryMinCents: 1000,
    prepTimeMinMinutes: 15,
    prepTimeMaxMinutes: 25,
    coverPicsumSeed: 'st-tropez-tacos',
    categories: [
      {
        name: 'Tacos',
        items: [
          {
            name: 'Carnitas (3)',
            description: 'Porc effiloché lent.',
            priceCents: 1290,
            allergens: ['gluten'],
          },
          {
            name: 'Pescado (3)',
            description: 'Poisson pané, sauce chipotle.',
            priceCents: 1390,
            allergens: ['gluten', 'poisson'],
          },
        ],
      },
    ],
  },

  // ─── CAGNES-SUR-MER (2) ───────────────────────────────────────────────────
  {
    slug: 'haut-de-cagnes',
    name: 'Haut-de-Cagnes',
    description: 'Bistrot perché, plats provençaux familiaux.',
    cuisines: [C.french, C.niçoise],
    city: 'Cagnes-sur-Mer',
    street: '10 montée de la Bourgade',
    postalCode: '06800',
    lat: 43.6648,
    lng: 7.149,
    priceRange: 2,
    rating: '4.5',
    ratingCount: 145,
    deliveryFeeCents: 299,
    deliveryMinCents: 1500,
    prepTimeMinMinutes: 25,
    prepTimeMaxMinutes: 40,
    isLocalSpecialty: true,
    coverPicsumSeed: 'cagnes-bistrot',
    categories: [
      {
        name: 'Plats',
        items: [
          {
            name: 'Petits farcis',
            description: '',
            priceCents: 1490,
            isLocalSpecialty: true,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
          { name: 'Daube niçoise', description: '', priceCents: 1890, isLocalSpecialty: true },
        ],
      },
    ],
  },
  {
    slug: 'sushi-cagnes',
    name: 'Sushi Cagnes',
    description: 'Sushi de quartier, frais et abordable.',
    cuisines: [C.japanese, C.sushi],
    city: 'Cagnes-sur-Mer',
    street: '32 avenue de Nice',
    postalCode: '06800',
    lat: 43.6611,
    lng: 7.1492,
    priceRange: 2,
    rating: '4.2',
    ratingCount: 178,
    deliveryFeeCents: 299,
    deliveryMinCents: 1500,
    prepTimeMinMinutes: 18,
    prepTimeMaxMinutes: 28,
    coverPicsumSeed: 'cagnes-sushi',
    categories: [
      {
        name: 'Plateaux',
        items: [
          {
            name: 'Plateau 24 pcs',
            description: 'Mix saumon, thon, makis.',
            priceCents: 2290,
            isPopular: true,
            allergens: ['poisson', 'soja', 'sésame'],
          },
          {
            name: 'Plateau veggie 18 pcs',
            description: '',
            priceCents: 1690,
            isVegetarian: true,
            allergens: ['soja', 'sésame'],
          },
        ],
      },
    ],
  },

  // ─── GRASSE (2) ────────────────────────────────────────────────────────────
  {
    slug: 'parfum-de-provence',
    name: 'Parfum de Provence',
    description: 'Cuisine du terroir grassois, herbes aromatiques.',
    cuisines: [C.french, C.mediterranean],
    city: 'Grasse',
    street: '4 place aux Aires',
    postalCode: '06130',
    lat: 43.6589,
    lng: 6.9221,
    priceRange: 2,
    rating: '4.6',
    ratingCount: 124,
    deliveryFeeCents: 299,
    deliveryMinCents: 1500,
    prepTimeMinMinutes: 22,
    prepTimeMaxMinutes: 35,
    isVegetarianFriendly: true,
    isLocalSpecialty: true,
    coverPicsumSeed: 'grasse-provence',
    categories: [
      {
        name: 'Plats',
        items: [
          {
            name: 'Lapin aux herbes',
            description: 'Romarin, thym, sariette.',
            priceCents: 1990,
            isGlutenFree: true,
          },
          {
            name: 'Tarte aux herbes',
            description: 'Blettes, chèvre frais.',
            priceCents: 1290,
            isVegetarian: true,
            allergens: ['gluten', 'oeuf', 'lait'],
          },
        ],
      },
    ],
  },
  {
    slug: 'grasse-veggie',
    name: 'Grasse Veggie',
    description: "Cantine végétale, du jardin à l'assiette.",
    cuisines: [C.vegan, C.healthy, C.vegetarian],
    city: 'Grasse',
    street: '15 boulevard du Jeu-de-Ballon',
    postalCode: '06130',
    lat: 43.6603,
    lng: 6.9249,
    priceRange: 2,
    rating: '4.4',
    ratingCount: 87,
    deliveryFeeCents: 299,
    deliveryMinCents: 1200,
    prepTimeMinMinutes: 15,
    prepTimeMaxMinutes: 25,
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    coverPicsumSeed: 'grasse-veggie',
    categories: [
      {
        name: 'Du jour',
        items: [
          {
            name: 'Bowl du jardinier',
            description: 'Légumes de saison, vinaigrette.',
            priceCents: 1290,
            isVegan: true,
            isGlutenFree: true,
          },
          {
            name: 'Tartine champignons',
            description: 'Pain au levain, champignons sautés.',
            priceCents: 990,
            isVegan: true,
            allergens: ['gluten'],
          },
        ],
      },
    ],
  },
];
